name: Release
run-name: Release collabora

on:
  push:
    tags:
      - release-*

jobs:
  build:
    runs-on: self-hosted
    container:
      image: klimarev/lo_co_build_env:1.10
      options:
        --user ghactions 
        -v /opt/libreoffice/android_armeabi-v7a_core_co-23.05.6-2:/opt/libreoffice/android_armeabi-v7a_core
        -v /opt/libreoffice/android_arm64-v8a_core_co-23.05.6-2:/opt/libreoffice/android_arm64-v8a_core
        -v /opt/libreoffice/android_x86_core_co-23.05.6-2:/opt/libreoffice/android_x86_core
        -v /opt/libreoffice/android_x86_64_core_co-23.05.6-2:/opt/libreoffice/android_x86_64_core
    env:
      app: android/build/app/outputs/apk
      lib: android/build/lib/outputs/aar
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build info 
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server!"
          echo "🔎 This job builds Collabora fork ${{ github.ref }} for adnroid."
          echo "This job is run from $(whoami)"
          echo "Current directory is $(pwd)"
          echo "Current directory structure: $(ls -la)"
          echo "/opt/libreoffice directory structure: $(ls -la /opt/libreoffice)"
          echo "CollaboraOnline directory size: $(du -sh .)"

      - name: Build ${{ github.ref }}
        run: |
          export workspace=/opt/libreoffice
          ./autogen.sh
          ./configure --enable-androidapp \
                      --with-lo-builddir=$workspace/android_armeabi-v7a_core:$workspace/android_arm64-v8a_core:$workspace/android_x86_core:$workspace/android_x86_64_core \
                      --with-poco-includes=$poco/include:$poco/include:$poco/include:$poco/include \
                      --with-poco-libs=$poco/armeabi-v7a/lib:$poco/arm64-v8a/lib:$poco/x86/lib:$poco/x86_64/lib \
                      --with-zstd-includes=$zstd/armeabi-v7a/include:$zstd/arm64-v8a/include:$zstd/x86/include:$zstd/x86_64/include \
                      --with-zstd-libs=$zstd/armeabi-v7a/lib:$zstd/arm64-v8a/lib:$zstd/x86/lib:$zstd/x86_64/lib \
                      --disable-setcap \
                      --enable-silent-rules
          make
          cd android
          ./gradlew --parallel build
        env:
          poco: /opt/android-poco
          zstd: /opt/android-zstd
          ANDROID_SDK_ROOT: /opt/android_sdk

      - name: Check if ${{ env.app }} contains build files
        continue-on-error: true
        run: |
          du -sh ${{ env.app }}
          ls -la ${{ env.app }}

      - name: Check if ${{ env.lib }} contains build files
        continue-on-error: true
        run: |
          du -sh ${{ env.lib }}
          ls -la ${{ env.lib }}
          
      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: ${{ env.app }}/release
          signingKeyBase64: ${{ secrets.COLLABORA_UPLOAD_KEYSTORE_JKS_BASE64 }}
          alias: ${{ secrets.COLLABORA_UPLOAD_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.COLLABORA_UPLOAD_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.COLLABORA_UPLOAD_KEY_PASSWORD }}
      
      - uses: jungwinter/split@v2.1.0
        id: signed_files
        with:
          msg: ${{ steps.sign_app.outputs.signedReleaseFiles }}
          separator: ':'

      - name: Example Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release collabora android app and libs"
          files: |
            ${{ steps.signed_files.outputs._0 }}
            ${{ steps.signed_files.outputs._1 }}
            ${{ steps.signed_files.outputs._2 }}
            ${{ steps.signed_files.outputs._3 }}
            ${{ env.lib }}/lib-debug.aar
            ${{ env.lib }}/lib-release.aar

      - run: echo "🍏 This job's status is ${{ job.status }}."
